### ISSUE TITLE
Max Enchant Levels Don't Change

### ISSUE THREAD

**Issue by Tradie18** [crashtheparty/EnchantmentSolution#60]
Players can still obtain enchantments even if you set a max level.

I have height++ set to 1, but people are still getting 2.

With /enchant info it still displays the default max level too. 

This is happening with both vanilla enchants and custom. Please fix this for the second time its so annoying.

They can also merge enchants in anvils to avoid it as well.

**Comment by crashtheparty** [comment]
Fixed in 2.2.6.

**Comment by Tradie18** [comment]
This is still not fixed mate. At least test before saying it is please. This is starting to get frustrating. 
![image](https://user-images.githubusercontent.com/59085649/74590769-717d6000-504c-11ea-9b2c-765588cc3c3a.png)


I have set the max level to 3, yet people can still merge picks together in anvils. The max levels in config are broken and do not work. FOR ANY enchant.

**Comment by crashtheparty** [comment]
I just tested in 2.2.6 and I am able to get normal behavior with this. Please make sure that you are not op, as you will always have the permission to combine levels; that you have advanced_options.use set to true, as that is required to use permissions; and that you have advanced_options.use_permissions set to true,
